name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Set current date
        id: set_date
        run: |
          echo "DATE=$( date '+%F-%H%M%S' )" >> "$GITHUB_ENV"
      -
        name: Get current date
        id: get_date
        run: |
          echo "${{ env.DATE }}"
